version: 2

sources:
  - name: office_weather
    schema: "{{target.schema}}"
    tables:
      - name: weather_readings

models:
  - name: stg_weather_data
    config:
     pre_hook: 
      - "{{ fetch_weather() }}"